name: Test

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: 1.97.1

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: test-${{ matrix.os }}
      - uses: taiki-e/install-action@nextest
      - run: cargo nextest run --all-features --no-tests warn
      - run: cargo test --doc --all-features
